name: tlv
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  graphql: ^5.1.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  flutter_lints: ^2.0.1
  logger: ^1.1.0
  injectable: ^2.1.0
  go_router: ^5.2.4
  easy_debounce: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  build_runner: ^2.3.0
  bloc_test: ^9.1.0
  mockito: ^5.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  dart_code_metrics: 4.19.2


flutter:
  uses-material-design: true
